import type { Metadata } from "next";
import { Geist_Mono, Onest } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Footer7 } from "@/components/footer7";
import { Navbar } from "@/components/navbar";
import ConvexClientProvider from "../ConvexClientProvider";

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${onest.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <ConvexClientProvider>
            <Navbar />
            {children}
            <Footer7 />
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
